#!/bin/sh
#
# Copyright (C) 2016, 2017  Qi Yong <qiy@vecl.cn>
#
# 2016-06-29

set -e
what="$1"
cmd="$2"

pkg_search() {
  if [ -e /etc/debian_version ]; then
    dpkg -S "$1"
  fi
  if [ -e /etc/redhat-release ]; then
    rpm -qf "$1"
  fi
}

if [ -z "$what" ]; then
  echo "what to tell you?"
  echo "usage: `basename $0` <what> [cmd]"
fi

if [ -n "$what" ]; then
  # locate what
  if [ -e "$what" ]; then
    file "$what"
    pkg_search "$what"
    exit 0
  fi

  pathname=`which "$what"`
  real_pathname=`realpath "$pathname"`
  if [ "$pathname" != "$real_pathname" ]; then
    file "$pathname"
  fi
  file "$real_pathname"
  pkg_search "$real_pathname"
fi

if [ -n "$cmd" ]; then
  $cmd "$real_pathname"
fi
